services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mydb" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
